"""correct external data entity_id nullable

Revision ID: 7650048c1bdf
Revises: a4374ccd19c1
Create Date: 2025-06-22 11:01:54.647600+00:00

"""

# mypy: ignore-errors

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7650048c1bdf"
down_revision: Union[str, None] = "a4374ccd19c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "external_data", "entity_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "external_data", "entity_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
